import { describe, it, expect } from "vitest";

import { isSmartGenerated, parseProvenance } from "../../provenanceParser";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const smartGeneratedYaml = `
cubes:
  - name: orders
    sql_table: public.orders
    meta:
      auto_generated: true
      source_database: analytics_db
      source_table: orders
      generated_at: "2026-03-10T12:00:00Z"
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
      - name: status
        sql: status
        type: string
    measures:
      - name: count
        type: count
`;

const smartGeneratedWithUserContent = `
cubes:
  - name: orders
    sql_table: public.orders
    meta:
      auto_generated: true
      source_database: analytics_db
      source_table: orders
      generated_at: "2026-03-10T12:00:00Z"
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
    measures:
      - name: count
        type: count
    joins:
      - name: users
        sql: "{CUBE}.user_id = {users}.id"
        relationship: many_to_one
    pre_aggregations:
      - name: main
        measures:
          - count
        time_dimension: created_at
        granularity: day
`;

const smartGeneratedWithSegments = `
cubes:
  - name: orders
    sql_table: public.orders
    meta:
      auto_generated: true
      source_database: warehouse
      source_table: fact_orders
      generated_at: "2026-03-09T08:00:00Z"
    dimensions:
      - name: id
        sql: id
        type: number
    segments:
      - name: completed
        sql: "{CUBE}.status = 'completed'"
`;

const nonGeneratedYaml = `
cubes:
  - name: custom_cube
    sql_table: public.custom
    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true
    measures:
      - name: count
        type: count
`;

const manualWithAutoFalse = `
cubes:
  - name: manual_cube
    sql_table: public.manual
    meta:
      auto_generated: false
    dimensions:
      - name: id
        sql: id
        type: number
`;

const jsModelWithAutoGenerated = `
cube(\`orders\`, {
  sql_table: \`public.orders\`,
  meta: {
    auto_generated: true,
    source_database: "analytics_db",
    source_table: "orders",
    generated_at: "2026-03-10T12:00:00Z",
  },
  dimensions: {
    id: { sql: \`id\`, type: \`number\`, primary_key: true },
  },
  measures: {
    count: { type: \`count\` },
  },
});
`;

const yamlWithPartition = `
cubes:
  - name: events
    sql_table: analytics.events
    meta:
      auto_generated: true
      source_database: clickhouse_prod
      source_table: events
      source_partition: "2026-03"
      generated_at: "2026-03-10T15:30:00Z"
    dimensions:
      - name: event_id
        sql: event_id
        type: string
`;

// ---------------------------------------------------------------------------
// Tests: isSmartGenerated
// ---------------------------------------------------------------------------

describe("isSmartGenerated", () => {
  it("returns true for YAML models with auto_generated: true", () => {
    expect(isSmartGenerated(smartGeneratedYaml)).toBe(true);
  });

  it("returns false for models without auto_generated meta", () => {
    expect(isSmartGenerated(nonGeneratedYaml)).toBe(false);
  });

  it("returns false for models with auto_generated: false", () => {
    expect(isSmartGenerated(manualWithAutoFalse)).toBe(false);
  });

  it("returns true for JS models with auto_generated: true", () => {
    expect(isSmartGenerated(jsModelWithAutoGenerated)).toBe(true);
  });

  it("returns false for empty string", () => {
    expect(isSmartGenerated("")).toBe(false);
  });

  it("returns true even when user content is present", () => {
    expect(isSmartGenerated(smartGeneratedWithUserContent)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Tests: parseProvenance
// ---------------------------------------------------------------------------

describe("parseProvenance", () => {
  it("extracts source_database, source_table, and generated_at", () => {
    const info = parseProvenance(smartGeneratedYaml);
    expect(info.sourceDatabase).toBe("analytics_db");
    expect(info.sourceTable).toBe("orders");
    expect(info.generatedAt).toBe("2026-03-10T12:00:00Z");
    expect(info.autoGenerated).toBe(true);
  });

  it("extracts source_partition when present", () => {
    const info = parseProvenance(yamlWithPartition);
    expect(info.sourceDatabase).toBe("clickhouse_prod");
    expect(info.sourceTable).toBe("events");
    expect(info.sourcePartition).toBe("2026-03");
    expect(info.generatedAt).toBe("2026-03-10T15:30:00Z");
  });

  it("detects user content when joins are present", () => {
    const info = parseProvenance(smartGeneratedWithUserContent);
    expect(info.hasUserContent).toBe(true);
    expect(info.autoGenerated).toBe(true);
  });

  it("detects user content when segments are present", () => {
    const info = parseProvenance(smartGeneratedWithSegments);
    expect(info.hasUserContent).toBe(true);
  });

  it("returns hasUserContent=false for pure auto-generated models", () => {
    const info = parseProvenance(smartGeneratedYaml);
    expect(info.hasUserContent).toBe(false);
  });

  it("returns all null fields for non-generated models", () => {
    const info = parseProvenance(nonGeneratedYaml);
    expect(info.sourceDatabase).toBeNull();
    expect(info.sourceTable).toBeNull();
    expect(info.sourcePartition).toBeNull();
    expect(info.generatedAt).toBeNull();
    expect(info.autoGenerated).toBe(false);
    expect(info.hasUserContent).toBe(false);
  });

  it("returns defaults for empty string", () => {
    const info = parseProvenance("");
    expect(info.sourceDatabase).toBeNull();
    expect(info.sourceTable).toBeNull();
    expect(info.autoGenerated).toBe(false);
    expect(info.hasUserContent).toBe(false);
  });

  it("extracts provenance from JS models", () => {
    const info = parseProvenance(jsModelWithAutoGenerated);
    expect(info.autoGenerated).toBe(true);
    expect(info.sourceDatabase).toBe("analytics_db");
    expect(info.sourceTable).toBe("orders");
  });
});
