/**
 * Parses provenance metadata from YAML cube definitions.
 * Used to detect smart-generated models and extract source information
 * for re-profiling and merge option defaults.
 */

interface ProvenanceInfo {
  sourceDatabase: string | null;
  sourceTable: string | null;
  sourcePartition: string | null;
  generatedAt: string | null;
  autoGenerated: boolean;
  hasUserContent: boolean;
}

/**
 * Extract provenance metadata from a YAML model's code string.
 * Looks for cube-level meta fields: auto_generated, source_database, source_table, etc.
 */
export function parseProvenance(code: string): ProvenanceInfo {
  const result: ProvenanceInfo = {
    sourceDatabase: null,
    sourceTable: null,
    sourcePartition: null,
    generatedAt: null,
    autoGenerated: false,
    hasUserContent: false,
  };

  if (!code) return result;

  // Check for auto_generated marker
  const autoGenMatch = code.match(/auto_generated:\s*(true|false)/);
  if (autoGenMatch) {
    result.autoGenerated = autoGenMatch[1] === "true";
  }

  // Extract source info from cube meta
  const dbMatch = code.match(/source_database:\s*["']?([^"'\n]+)["']?/);
  if (dbMatch) result.sourceDatabase = dbMatch[1].trim();

  const tableMatch = code.match(/source_table:\s*["']?([^"'\n]+)["']?/);
  if (tableMatch) result.sourceTable = tableMatch[1].trim();

  const partitionMatch = code.match(/source_partition:\s*["']?([^"'\n]+)["']?/);
  if (partitionMatch) result.sourcePartition = partitionMatch[1].trim();

  const generatedMatch = code.match(/generated_at:\s*["']?([^"'\n]+)["']?/);
  if (generatedMatch) result.generatedAt = generatedMatch[1].trim();

  // Detect user content: any field/block without auto_generated meta
  // Simple heuristic: check for joins, pre_aggregations, segments
  if (
    code.includes("joins:") ||
    code.includes("pre_aggregations:") ||
    code.includes("segments:")
  ) {
    result.hasUserContent = true;
  }

  return result;
}

/**
 * Check if a model file is a smart-generated model that can be re-profiled.
 */
export function isSmartGenerated(code: string): boolean {
  return parseProvenance(code).autoGenerated;
}
